### ISSUE TITLE
Jumping auto-insert

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#129]
**To Reproduce**

- Create a todo like this: ` Todo +lorem_ipsum`
- Create another: ` Todo +loremdolor`
- Click the second todo to edit.
- Type `+lo`
- Click the suggested project `lorem_ipsum`

**Expected behavior**

- The second `+lorem_ipsum` is added next to the first like this:
` Todo +loremdolor +lorem_ipsum`

**Actual behavior**

- The line is jumbled:
`Testremdolor +lo +lorem_ipsum `

---
**Note**:
1. It seems to follow the pattern:

    - `Test` = Plain text of the todo
    -  `remdolor` = Second part of the existing project (everything after the typed part `lo` which is the common prefix of both.
    - {space}
    - `+lo` = Typed part
    - {space}
    - `+lorem_ipsum` = The new project.
    - {space}

    So for example if you typed `+lore` and clicked `lorem_ipsum`, it would be Test*mdolor* +*lore* +**lorem_ipsum** :
    - `Test`
    - `mdolor`
    - {space}
    - `+lore`
    - {space}
    - `+lorem_ipsum`
    - {space}

2. It happens whenever the clicked project shares a common prefix with an existing one.
3. It would happen even if the clicked project is the same as the exiting one (no need to have a second todo or a second project).
4. It doesn't happen if you type past the common prefix. For example, type `+lorem_` and click `lorem_ipsum`. Expected behavior.

---

**Desktop:**
 - Windows 10
 - sleek 1.0.4
 - Source: Github

**Comment by ransome1** [comment]
Hi @9z0, thanks, that was a nice one. Can you check if this still occurs in https://github.com/ransome1/sleek/releases/tag/v1.0.5-2?

**Comment by 9z0** [comment]
Seems to work fine 👍

**Comment by 9z0** [comment]
Update: The described form doesn't happen anymore, but some jumbling happened twice since then. I tried to reproduce it immediately after, but it didn't occur. Maybe a race condition or something similar is still at play?

**Comment by ransome1** [comment]
@9z0 I rechecked your aboved mentioned example a couple of times also in different combinations and with contexts instead of projects. So far I could not experience any issue or glitch.

I'm going to close here. If this issues persists in any way, please let me know and we continue working in this ticket.

**Comment by 9z0** [comment]
Related issue: if you are in the middle of the typed part, then click a suggestion, it is jumbled.

For example, type `+loem`, go back to insert the `r` (for `lorem`), click `lorem_ipsum` (while the cursor is after the `r`).

Not a very common scenario (just discovered it), but happens.

**Comment by ransome1** [comment]
Yep, you're right, this still is an issue.

**Comment by ransome1** [comment]
@9z0 does this still happen on your side in https://github.com/ransome1/sleek/releases/tag/v1.0.8?

**Comment by 9z0** [comment]
> @9z0 does this still happen on your side in https://github.com/ransome1/sleek/releases/tag/v1.0.8?

Not any more! 👍

**Comment by ransome1** [comment]
@9z0 you're right. I think I just fixed it on my side. With the next release I'm going to ask you again ;)

**Comment by 9z0** [comment]
It does seem fixed. So far so good!

**Comment by 9z0** [comment]
But now the [second form](#issuecomment-855163943) of the bug is back!!

**Comment by ransome1** [comment]
@9z0 both cases should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.0.9-rc.4

**Comment by 9z0** [comment]
I can cautiously confirm!

**Comment by ransome1** [comment]
Thanks for your feedback!
