### ISSUE TITLE
Application opens empty and unable to open any todo.txt

### ISSUE THREAD

**Issue by warmwaffles** [ransome1/sleek#558]
## Bug Report

**App Version:** 2.0.0

**Platform:** Linux

**Window Manager:** BSPWM

**Installation Method:** AUR

**Bug Description:**
When I open sleek, I am greeted with an empty application. The file menu works, I can not open the developer console.

**Steps to Reproduce:**
1. Using the `PKGBUILD` run `makepkg -sci`
2. Launch sleek via the command line to get logger errors

**Expected Behavior:**
Expected the app to not be blank 🤣 

**Actual Behavior:**
Application opens empty

**Additional Information:**

```
config.ts: sleek userdata is located at: /home/warmwaffles/.config/sleek/userData
(node:131279) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `electron --trace-warnings ...` to show where the warning was created)
[131279:1031/162325.931193:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[131279:1031/162325.931219:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
main.ts: Menu created
main.ts: Tray not shown
main.ts: TypeError: Error processing argument at index 0, conversion failure from undefined
    at Ke (/usr/lib/sleek.asar/dist/main/main.js:8:269372)
    at /usr/lib/sleek.asar/dist/main/main.js:8:270308
[131279:1031/162325.968910:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

**Screenshots:**

![20231031-162756](https://github.com/ransome1/sleek/assets/303133/6ddb6c0b-636c-42e4-9bde-d1dcd0f928a6)

**Comment by ransome1** [comment]
Is fixed and will be part of 2.0.1 :)

**Comment by warmwaffles** [comment]
`v2.0.1` resolves this issue. I had to delete all of my configurations to stop the blank screen from happening.

**Comment by gladomat** [comment]
It still won't work for me for 2.0.6.

Here's what I'm seeing

```
config.ts: sleek userdata is located at: /home/xxx/snap/sleek/1193/.config/sleek/userData
[2898185:0118/161229.499765:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.ListActivatableNames: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.5162" (uid=1000 pid=2898185 comm="/snap/sleek/1193/sleek/sleek --disable-gpu --no-sa" label="snap.sleek.sleek (enforce)") interface="org.freedesktop.DBus" member="ListActivatableNames" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
[2898185:0118/161229.526247:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.ListNames: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.5164" (uid=1000 pid=2898185 comm="/snap/sleek/1193/sleek/sleek --disable-gpu --no-sa" label="snap.sleek.sleek (enforce)") interface="org.freedesktop.DBus" member="ListNames" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
[2898185:0118/161229.557359:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.ListNames: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.5165" (uid=1000 pid=2898185 comm="/snap/sleek/1193/sleek/sleek --disable-gpu --no-sa" label="snap.sleek.sleek (enforce)") interface="org.freedesktop.DBus" member="ListNames" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
Styles injected found in CSS file: /home/xxx/snap/sleek/1193/.config/sleek/userData/customStyles.css
```
